import { useState } from "react";
import { useChatContext } from "../../context/ChatContext";
import ConversationItem from "./ConversationItem";
import ConversationContextMenu from "./ConversationContextMenu";
import { MessageSquare, Sparkles } from "lucide-react";

const Conversations = ({ searchQuery, filterChip, onSelectAI, isAISelected }) => {
  const {
    conversations,
    allUsers,
    selectedConversation,
    setSelectedConversation,
    loadingConversations
  } = useChatContext();

  const [contextMenu, setContextMenu] = useState(null); // { x, y, user }

  // Combine recent conversations and all contacts
  const combinedList = conversations.length > 0 ? conversations : allUsers;

  // Filter based on search and chip
  const filteredList = (filterChip === "groups"
    ? combinedList.filter((c) => c.isGroup)
    : filterChip === "unread"
    ? combinedList.filter((_, idx) => idx % 2 === 0)
    : combinedList
  ).filter((user) => {
    if (!searchQuery) return true;
    const q = searchQuery.toLowerCase();
    return (
      user.fullname?.toLowerCase().includes(q) ||
      user.username?.toLowerCase().includes(q)
    );
  });

  const handleContextMenu = (e, user) => {
    e.preventDefault();
    setContextMenu({
      x: e.clientX,
      y: e.clientY,
      user
    });
  };

  return (
    <div className="flex-1 min-h-0 overflow-y-auto pr-0.5 relative">
      {/* 🔮 Aryavarta AI Pinned Card matching Meta AI in screenshot */}
      {(!filterChip || filterChip === "all") && !searchQuery && (
        <div
          onClick={onSelectAI}
          className={`group relative flex items-center gap-3 px-3 py-3 cursor-pointer transition-all border-b border-slate-800/60 select-none ${
            isAISelected
              ? "bg-[#2a3942] text-white"
              : "hover:bg-[#202c33] text-slate-300"
          }`}
        >
          {/* Purple Swirl Logo */}
          <div className="relative flex-shrink-0">
            <div className="w-12 h-12 rounded-full bg-gradient-to-tr from-purple-600 via-pink-600 to-indigo-600 p-0.5 flex items-center justify-center shadow-lg shadow-purple-600/30">
              <div className="w-full h-full bg-[#111b21] rounded-full flex items-center justify-center">
                <Sparkles className="w-5 h-5 text-purple-400 animate-spin-slow" />
              </div>
            </div>
            <span className="absolute -top-0.5 -right-0.5 w-2.5 h-2.5 bg-purple-400 rounded-full animate-ping" />
          </div>

          <div className="flex-1 min-w-0">
            <div className="flex items-center justify-between mb-1">
              <div className="flex items-center gap-1.5">
                <h4 className="text-sm font-bold text-slate-100 group-hover:text-purple-300 transition-colors">
                  Aryavarta AI
                </h4>
                <span className="text-purple-400 text-xs">✨</span>
              </div>
              <span className="text-[11px] text-slate-400 flex-shrink-0">5:48 pm</span>
            </div>

            <p className="text-xs text-slate-400 truncate">
              Messages are generated by Aryavarta AI. Some may...
            </p>
          </div>
        </div>
      )}

      {loadingConversations ? (
        Array.from({ length: 6 }).map((_, idx) => (
          <div
            key={idx}
            className="flex items-center gap-3 px-3 py-3 border-b border-slate-800/40 animate-pulse"
          >
            <div className="w-12 h-12 rounded-full bg-slate-800 flex-shrink-0" />
            <div className="flex-1 space-y-2">
              <div className="h-3.5 bg-slate-700/50 rounded w-2/3" />
              <div className="h-2.5 bg-slate-700/30 rounded w-1/2" />
            </div>
          </div>
        ))
      ) : filteredList.length > 0 ? (
        filteredList.map((user, idx) => (
          <ConversationItem
            key={user._id}
            user={user}
            isSelected={!isAISelected && selectedConversation?._id === user._id}
            onClick={() => setSelectedConversation(user)}
            onContextMenu={(e) => handleContextMenu(e, user)}
            unreadCount={idx === 1 ? 73 : idx === 2 ? 46 : idx === 3 ? 35 : idx === 4 ? 18 : 0}
          />
        ))
      ) : (
        <div className="flex flex-col items-center justify-center h-48 text-center p-4">
          <div className="w-12 h-12 rounded-full bg-slate-800 flex items-center justify-center mb-2 text-slate-400">
            <MessageSquare className="w-6 h-6 text-[#00a884]" />
          </div>
          <p className="text-sm font-semibold text-slate-200">
            {searchQuery ? "No matches found" : "No chats yet"}
          </p>
          <p className="text-xs text-slate-500 mt-1 max-w-[200px]">
            {searchQuery
              ? "Try searching for a different contact name"
              : "Start a conversation with contacts from the directory!"}
          </p>
        </div>
      )}

      {/* Right-click Context Menu */}
      {contextMenu && (
        <ConversationContextMenu
          x={contextMenu.x}
          y={contextMenu.y}
          user={contextMenu.user}
          onClose={() => setContextMenu(null)}
        />
      )}
    </div>
  );
};

export default Conversations;
